TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
  LIB_REQUIRED_PACKAGES PanzerCore PanzerDofMgr PanzerDiscFE PanzerAdaptersSTK Phalanx Belos Teko MueLu
  LIB_OPTIONAL_PACKAGES ML
  TEST_REQUIRED_PACKAGES
  TEST_OPTIONAL_PACKAGES
  LIB_REQUIRED_TPLS MPI
  LIB_OPTIONAL_TPLS PAPI CAMAL
  TEST_REQUIRED_TPLS
  TEST_OPTIONAL_TPLS
  )

